### ISSUE TITLE
a manager can add a new apartment complex

### ISSUE THREAD

**Issue by christianroach** [java24july-ank-meh/The-Exceptionals#13]

**Comment by HurielHernandez** [comment]
Create new apartment complex form is done on the AngularJS side.  

json data sent  as POST to: /RevatureHousingManagementSystem/api/ApartmentComplexes/create

Expecting 201 or 200 response for successfully created along with the id of the newly created complex for sucess.

Expecting an error code response along with a generic error message in json should an error occur.
